api_platform:
  title: Hello API Platform
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
  mapping:
    paths: ['%kernel.project_dir%/src/Dto']
  formats:
    jsonld: ['application/ld+json']
    json: [ 'application/json' ]
  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
  resource_class_directories:
    - '%kernel.project_dir%/src/Entity'
